annonce_homepage:
    path:     /
    defaults: { _controller: AnnonceBundle:Default:index }

##### Nidhal

SkillsRead:
  path:     /Skills
  defaults: { _controller: AnnonceBundle:Skills:ReadSkills }

SkillsCreate:
  path:     /Skills/Create
  defaults: { _controller: AnnonceBundle:Skills:CreateSkills }

SkillsDelete:
  path:     /Skills/Delete/{id}
  defaults: { _controller: AnnonceBundle:Skills:DeleteSkills }

SkillsUpdate:
  path:     /Skills/Update/{id}
  defaults: { _controller: AnnonceBundle:Skills:UpdateSkills }

UsContact :
  path:     /ContactUs
  defaults: { _controller: AnnonceBundle:Default:ContactUs }

AdminAccueil :
  path:     /AccueilAdmin
  defaults: { _controller: AnnonceBundle:Default:AccueilAdmin }

ClientAccueil :
  path:     /AccueilClient
  defaults: { _controller: AnnonceBundle:Default:AccueilClient }

FreelancerAccueil :
  path:     /AccueilFreelancer
  defaults: { _controller: AnnonceBundle:Default:AccueilFreelancer }

AdminProfil :
  path:     /ProfilAdmin
  defaults: { _controller: AnnonceBundle:Profil:ReadProfilA }

ClientProfil :
  path:     /ProfilClient
  defaults: { _controller: AnnonceBundle:Profil:ReadProfilC }

FreelancerProfil :
  path:     /ProfilFreelancer
  defaults: { _controller: AnnonceBundle:Profil:ReadProfilF }

AddSkill :
  path:     Skills/AddSkills
  defaults: { _controller: AnnonceBundle:Skills:AddSkill }

UpdateSk:
  path:     /Skills/Up/{id}
  defaults: { _controller: AnnonceBundle:Skills:updateSkill }

sendMail:
  path:     /mail
  defaults: { _controller: AnnonceBundle:Default:SendEmail }

sendMailAdmin:
  path:     /mailAdmin
  defaults: { _controller: AnnonceBundle:Default:SendEmail1 }


#### Kaffel

Annonce_home:
  path:     /Affiche
  defaults: { _controller: AnnonceBundle:Annonce:Affiche }

Annonce_home1:
  path:     /Affiche1
  defaults: { _controller: AnnonceBundle:Annonce:home }

Annonce_read:
  path:     /Read/{nom}
  defaults: { _controller: AnnonceBundle:Annonce:read }

Annonce_list:
  path:     /List
  defaults: { _controller: AnnonceBundle:Annonce:List }

Annonce_show:
  path:     /Show/{id}
  defaults: { _controller: AnnonceBundle:Annonce:showDetail }

Annonce_read1:
  path:     /Read1
  defaults: { _controller: AnnonceBundle:Annonce:read1 }

delete:
  path:     /delete/{id}
  defaults: { _controller: AnnonceBundle:Annonce:delete }

modifier:
  path:   /modif/{id}
  defaults: { _controller: AnnonceBundle:Annonce:modifier }

Add:
  path:   /Add
  defaults: { _controller: AnnonceBundle:Annonce:create }

ajouter1:
  path:   /Add1
  defaults: { _controller: AnnonceBundle:Annonce:ajouter1 }

update:
  path:   /Up/{id}
  defaults: { _controller: AnnonceBundle:Annonce:update }

Annonce_read2:
  path:     /Read2
  defaults: { _controller: AnnonceBundle:Annonce:read2 }

Addp:
  path:   /Addp/{idannonce}
  defaults: { _controller: AnnonceBundle:Annonce:create4 }

Annonce_read3:
  path:     /Read3
  defaults: { _controller: AnnonceBundle:Annonce:read3 }

update2:
  path:   /Up2/{id}
  defaults: { _controller: AnnonceBundle:Annonce:update2 }

delete2:
  path:     /delete2/{id}
  defaults: { _controller: AnnonceBundle:Annonce:delete2 }

Postulation:
  path:     /postulation/{id}
  defaults: { _controller: AnnonceBundle:Annonce:showPostule }

Postulationok:
  path:     /postek/{id}
  defaults: { _controller: AnnonceBundle:Annonce:postuleok }

histoClient:
  path:     /historiqueAnnonce
  defaults: { _controller: AnnonceBundle:Annonce:affhistorique }

histo:
  path:     /job
  defaults: { _controller: AnnonceBundle:Annonce:job }

######Yasser

club_redirect:
  path:     /smart/home
  defaults: { _controller: AnnonceBundle:Security:Redirect }

freelancerv_modifier:
  path:     /modifieEtat/{id}
  defaults: { _controller: AnnonceBundle:AdminF:update }

smart_showfeed:
  path:     /show
  defaults: { _controller: AnnonceBundle:Feedback:read }

smart_Create:
  path:     /create
  defaults: { _controller: AnnonceBundle:Feedback:create }

read_note:
  path:     /note
  defaults: { _controller: AnnonceBundle:Note:recherche}

club_modifier:
  path:     /modifie/{id}
  defaults: { _controller: AnnonceBundle:Feedback:update }

club_supprimer:
  path:     /supprime/{id}
  defaults: { _controller: AnnonceBundle:Feedback:supprimer }

creat_note:
  path:     /creatnote
  defaults: { _controller: AnnonceBundle:Note:creat }

supprimer_note:
  path:     /supprimer/{id}
  defaults: { _controller: AnnonceBundle:Note:supprimernote }

##### Farah

ticket_homepage:
  path:     /
  defaults: { _controller: AnnonceBundle:Default:index }

ticket_gestion:
  path:     /Affiche2
  defaults: { _controller: AnnonceBundle:Ticket:affiche }

delete1:
  path:     /delete1/{id}
  defaults: { _controller: AnnonceBundle:Ticket:delete }

Add1:
  path:     /Ajout1
  defaults: { _controller: AnnonceBundle:Ticket:create }

edit:
  path:     /edit/{id}
  defaults: { _controller: AnnonceBundle:Ticket:edit }

ticket_rechercher:
  path:     /rechercher
  defaults: { _controller: AnnonceBundle:Ticket:rechercher }

Ticket_AfficheH:
  path:     /readH
  defaults: { _controller: AnnonceBundle:Historiquereclamation:readH }

createH:
  path:     /createH
  defaults: { _controller: AnnonceBundle:Historiquereclamation:createH }

editH:
  path:     /editH/{id}
  defaults: { _controller: AnnonceBundle:Historiquereclamation:editH }

deleteH:
  path:     /deleteH/{id}
  defaults: { _controller: AnnonceBundle:Historiquereclamation:deleteH }

ticket_rechercherH:
  path:     /rechercherH
  defaults: { _controller: AnnonceBundle:Historiquereclamation:rechercherH }

categorie_gestion:
  path:     /Afficher
  defaults: { _controller: AnnonceBundle:Categoriereclamation:afficher }

deleter:
  path:     /deleter/{id}
  defaults: { _controller: AnnonceBundle:Categoriereclamation:deleter }

Addr:
  path:     /Ajoutr
  defaults: { _controller: AnnonceBundle:Categoriereclamation:creater }

editr:
  path:     /editr/{id}
  defaults: { _controller: AnnonceBundle:Categoriereclamation:editr }

ticket_rechercherr:
  path:     /rechercherr
  defaults: { _controller: AnnonceBundle:Categoriereclamation:rechercherr}

client_gestion:
  path:     /AfficheC
  defaults: { _controller: AnnonceBundle:User:AfficheC }

deleteC:
  path:     /deleteC/{id}
  defaults: { _controller: AnnonceBundle:User:deleteC }

createE:
  path:     /createE
  defaults: { _controller: AnnonceBundle:Default:createE }

edite:
  path:   /edite/{id}
  defaults: { _controller: AnnonceBundle:Historiquereclamation:edite }

show:
  path:     /show
  defaults: { _controller: AnnonceBundle:Ticket:show }

ticket_gestion2:
  path:     /Affiche3
  defaults: { _controller: AnnonceBundle:Ticket:affiche2 }

delete3:
  path:     /delete3/{id}
  defaults: { _controller: AnnonceBundle:Ticket:delete2 }

Add2:
  path:     /Ajout2
  defaults: { _controller: AnnonceBundle:Ticket:create2 }

edit2:
  path:     /edit2/{id}
  defaults: { _controller: AnnonceBundle:Ticket:edit2 }

#### Loua

formation_homepage:
  path:     /
  defaults: { _controller: AnnonceBundle:Default:index }

accueilC:
  path:     /accueilC
  defaults: { _controller: AnnonceBundle:Formation:accueilC }

accueilF:
  path:     /accueilF
  defaults: { _controller: AnnonceBundle:Formation:accueilF }


afficheFormationClient:
  path:   /afficheFormationClient
  defaults: { _controller: AnnonceBundle:Formation:affiche }

detail1:
  path:     /detail1/{id}
  defaults: { _controller: AnnonceBundle:Formation:detail1 }

deleteL:
  path:     /deleteL/{id}
  defaults: { _controller: AnnonceBundle:Formation:deleteL }

AddL:
  path:     /Ajout
  defaults: { _controller: AnnonceBundle:Formation:create }

updateL:
  path:     /update/{id}
  defaults: { _controller: AnnonceBundle:Formation:update }

chart:
  path:   /chart
  defaults: { _controller: AnnonceBundle:Stat:stat }

chart1:
  path:   /chart1
  defaults: { _controller: AnnonceBundle:Stat:chart }

afficheFormationFreelancer:
  path:   /afficheFormationFreelancer
  defaults: { _controller: AnnonceBundle:Formation:accueil }

affiche:
  path:   /showww
  defaults: { _controller: AnnonceBundle:Categorie:afficheC }

AddC:
  path:     /AjoutC
  defaults: { _controller: AnnonceBundle:Categorie:createC }

deleteCCL:
  path:     /deleteCC/{id}
  defaults: { _controller: AnnonceBundle:Categorie:deleteCC }

updateC:
  path:     /updateC/{id}
  defaults: { _controller: AnnonceBundle:Categorie:updateC }

participer:
  path:     /participer/{id}
  defaults: { _controller: AnnonceBundle:Formation:participer }

annuler:
  path:     /annuler/{id}
  defaults: { _controller: AnnonceBundle:Formation:annuler }

acceptee:
  path:     /acceptee
  defaults: { _controller: AnnonceBundle:Formation:acceptee }

list:
  path:     /list
  defaults: { _controller: AnnonceBundle:Formation:list }

list2:
  path: /list2/{id}
  defaults: { _controller: AnnonceBundle:Formation:list2 }

################### MOBILE ########################

######### Mobile Nidhal
Json_skills:
  path: /profile/skills
  defaults: { _controller: AnnonceBundle:Default:JsonSkillsAffiche }

Json_skillAdd:
  path: /skillsAdd
  defaults: { _controller: AnnonceBundle:Default:JsonAddSkill }

Json_profileFUP:
  path: /profileFUP/{id}
  defaults: { _controller: AnnonceBundle:Default:JsonModifyProfile }

Json_skillDelete:
  path: /skillsDelete/{id}
  defaults: { _controller: AnnonceBundle:Default:JsonDeleteSkill }
