ticket_homepage:
    path:     /
    defaults: { _controller: TicketBundle:Default:index }

ticket_gestion:
    path:     /Affiche
    defaults: { _controller: TicketBundle:Ticket:affiche }

delete:
    path:     /delete/{id}
    defaults: { _controller: TicketBundle:Ticket:delete }

Add:
    path:     /Ajout
    defaults: { _controller: TicketBundle:Ticket:create }

edit:
    path:     /edit/{id}
    defaults: { _controller: TicketBundle:Ticket:edit }

ticket_rechercher:
    path:     /rechercher
    defaults: { _controller: TicketBundle:Ticket:rechercher }

Ticket_AfficheH:
    path:     /readH
    defaults: { _controller: TicketBundle:Historiquereclamation:readH }

createH:
    path:     /createH
    defaults: { _controller: TicketBundle:Historiquereclamation:createH }


editH:
    path:     /editH/{id}
    defaults: { _controller: TicketBundle:Historiquereclamation:editH }

deleteH:
    path:     /deleteH/{id}
    defaults: { _controller: TicketBundle:Historiquereclamation:deleteH }

ticket_rechercherH:
    path:     /rechercherH
    defaults: { _controller: TicketBundle:Historiquereclamation:rechercherH }



categorie_gestion:
    path:     /Afficher
    defaults: { _controller: TicketBundle:Categoriereclamation:afficher }

deleter:
    path:     /deleter/{id}
    defaults: { _controller: TicketBundle:Categoriereclamation:deleter }

Addr:
    path:     /Ajoutr
    defaults: { _controller: TicketBundle:Categoriereclamation:creater }

editr:
    path:     /editr/{id}
    defaults: { _controller: TicketBundle:Categoriereclamation:editr }

ticket_rechercherr:
    path:     /rechercherr
    defaults: { _controller: TicketBundle:Categoriereclamation:rechercherr}


client_gestion:
    path:     /AfficheC
    defaults: { _controller: TicketBundle:User:AfficheC }

deleteC:
    path:     /deleteC/{id}
    defaults: { _controller: TicketBundle:User:deleteC }


createE:
    path:     /createE
    defaults: { _controller: TicketBundle:Default:createE }

edite:
    path:   /edite/{id}
    defaults: { _controller: TicketBundle:Historiquereclamation:edite }

show:
    path:     /show
    defaults: { _controller: TicketBundle:Ticket:show }