smart_start_homepage:
    path:     /
    defaults: { _controller: SmartStartBundle:Default:index }

SkillsRead:
    path:     /Skills
    defaults: { _controller: SmartStartBundle:Skills:ReadSkills }

SkillsCreate:
    path:     /Skills/Create
    defaults: { _controller: SmartStartBundle:Skills:CreateSkills }

SkillsDelete:
    path:     /Skills/Delete/{id}
    defaults: { _controller: SmartStartBundle:Skills:DeleteSkills }

SkillsUpdate:
    path:     /Skills/Update/{id}
    defaults: { _controller: SmartStartBundle:Skills:UpdateSkills }